export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const PILE_CHOOSEN = 'PILE_CHOOSEN';
export const PILE_CHOOSEN_SUCCESS = 'PILE_CHOOSEN_SUCCESS';
export const PILE_CHOOSEN_FAILURE = 'PILE_CHOOSEN_FAILURE';
export const LISTENING = 'LISTENING';